### ISSUE TITLE
generate ?[]T the same as []T, and use the NULL pointer value

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#293]

**Comment by thejoshwolfe** [comment]
that would mean that a non-null slice of len 0 would need to ensure that its pointer isn't 0. with a normal slice, you need to check the len first to see if the pointer is meaningful. but with your proposal for a maybe slice, you'd first check that the pointer isn't null, and then check that the len isn't 0, and then go back to the pointer for the elements.

seems like a clever use of undefined values, but do we really want to be that clever? it might incur some strange needs for runtime checks.

**Comment by andrewrk** [comment]
I'm not sure I agree that it incurs any extra runtime checks. This should be only a difference in the generated code. If the type is `?[]T` zig users already have to check that the slice isn't null before using it.

Is this not merely an optimization?

**Comment by thejoshwolfe** [comment]
```zig
fn getSlice() -> []u8 {
    return []u8{}; // {.ptr = undefined, .len = 0,}
}
fn getMaybeSlice() -> ?[]u8 {
    return getSlice(); // just leave it alone?
    // or check if .len == 0, and then set .ptr = 1?
}
```

We could solve this by making any 0-len slice always set its .ptr to non-0. Rather than leaving it undefined; set it to 1 or something silly like that. But up until this proposal, leaving the .ptr as undefined was some combination of optimization, safety, and correctness.

Also consider `[]void`, which has a 0-bit .ptr field, leaving the slice effectively equivalent to a `usize`. We'd still need to add data to make that into a maybe type.

**Comment by andrewrk** [comment]
OK, I see, thanks for the example.

I wish I typed up an explanation for this issue. I feel like I had some reasoning at the time for why it made sense but now I don't remember.
