### ISSUE TITLE
proposal: different way to specify exported symbols

### ISSUE THREAD

**Issue by andrewrk** [zig-lang/zig#462]
Problem: We have some messy complications regarding the difference between pub and export.

 * `pub`, `export`, and unqualified are the 3 visibility modifiers. Pub makes sense. But if it's `export` then it goes into the global namespace as well as being exposed in the current module.
 * `export` automatically changes the calling convention of a function to C calling convention, which is represented in type syntax as `extern fn()`
 * `extern fn();` also changes calling convention to CCC.
 * We also have `nakedcc`, `stdcallcc`, `coldcc`. But no `ccc`.
 * `export`ed functions have special requirements such as disallowing comptime parameters and use of certain types.
 * when you `@import` a module which exported a function, that function name is meant for the global namespace, but you're going to call it through a module namespace.
 * we have `extern fn() { ... } ` for a function definition that wants the C calling convention but does not need to be exported.
 * we also want to export types like structs and enums. That looks like `export const Foo = extern struct { ... }`.
 * aliases is a thing. #420 

Here's the proposal:

 * Add this syntax:
```zig
export name = value;
```
 * Remove `export` from functions and global variables. (and generally remove it as a visibility modifier)
 * Add `ccc` as a calling convention. Use `ccc fn()` instead of `extern fn()` for the type syntax.
 * When you export a function, it gives compile errors if the function disobeys the exported function rules. Same with types.

I think this solves all the problems.

**Comment by kyle-github** [comment]
When I made the comments last night I had not put together all the parts.   It seems like there are a few mostly-orthogonal things here:

- visibility from users of the module/namespace.
- visibility at a global level (perhaps a degenerate condition of the above?)
- calling convention

The reason I say mostly-orthogonal is, as you point out, that you need to have both a "global" visibility on a function and have it use the C calling convention in order for C code to call it.   So the new export syntax above is only for things visible to C?   

As I understand it (and maybe I am missing something important due to my lack of experience with Zig!), a C-callable function differs in two ways from a standard Zig function.   It must be visible at the global level and it must use the C calling convention.   So you would still use "pub" for module-level entities, right?

Would there be a use case for global entities that are not C-callable?   If so, maybe then "export" becomes "global" and you retain the ccc part??

As a random thought (not very thought through), what if you mirrored @import with an @export?   Instead of a path to the file, you could have the namespace to which to export:

`
@export("io.file",FileHandle); /// FileHandle ends up as io.file.FileHandle
@export("",globalFunction);  /// globalFunction ends up globally visible without a module qualifier
@export("C",c_callable_func);  /// c_callable_func must have C calling convention
....
`

One thing that this would do is allow you to break the dependency between the file and module.   That is one thing that some languages manage to work around and it is really nice because you can inject more methods into a module after the fact.   Go has a pretty good way of extending types though in practice, it is apparently a source of boilerplate and fragility (I do not code in Go, so take that with a grain of salt).

One interesting thing about forcing a namespace for the type of exported function is that you could (if you were a masochist) also support the "C++" namespace and the "Fortran" namespace and...

Problems with this include divorcing the act of exporting the entity from the definition of the entity itself.   That lack of coupling means that it is easier to make mistakes by changing one part but not the other.

There are interesting things that were tried in JavaScript and in Java.   I worked with Smalltalk a long time ago and so the association between a file and a logical unit of the program has always been a point of some frustration for me.   

Any of the attempts I have made at languages that even had the concept of a file (images can be very powerful) tended to use convention over configuration.   A directory was a module.  A file within a directory automatically exported the type or function with the same name as the file.   Functions and data types that did not have the same name as the file were private to the module.   There was no syntax in the language to show exports.

Go's method of showing public exports by simply capitalizing the first letter of the name is actually quite nice because it is so simple.    It is hard to make a mistake and it does not clutter up the language syntax.

Not enough sleep last night as I am clearly starting to wander into the weeds :-)

**Comment by PavelVozenilek** [comment]
I have related proposal. Modules (or packages) provide several features:

1. Fast compilation, usually by not standing in the way.
2. Namespacing. Most common use but IMHO overrated. C++ does it wrong, Nim better.
3. **Encapsulation**. C/C++ has only very limited form - statics and anonymous namespaces.
4. In the most extreme interpretation modules also deal with dynamically loaded code.

Here's the proposal about **encapsulation**:

1. Source file is module. `foo.zig` is module `foo` (together with its directory path).  It could export functions, these are visible according to the rules.
2. **If subdirectory named `foo` exists in the same place as `foo.zig`** then this subdirectory and everything inside it is private implementation of the `foo` module.
3. Private implementation of a module has *no chance* to escape out, regardless of their export/pub annotations. It could be invoked only from the `foo` module but by nobody else.

This way one could:
1. Download 3rd party library, put it in private, wrap and export the desired parts. The un-needed rest of the library code won't be visible. There will be no name clashes. Library code would not need to be touched at all.
2. Clone existing code, make modifications and place the new version as private implementation somewhere. Again - no name clashes possible. This could be used e.g to compare performance between different versions.
3. Just looking on file names would be enough to know what is the interface (file `foo.zig`) and what is private implementation (`foo` directory). Time needed to grok a system would be reduced.
4. Experiment and explore safely. Source files could be freely copied or cloned, without the need to make changes inside, and without fears of silently breaking something.

**Comment by andrewrk** [comment]
This proposal also makes things like this more clear:

```zig
export nakedcc fn __chkstk() {
    @setDebugSafety(this, false);

    if (comptime builtin.os == builtin.Os.windows) {
        if (comptime builtin.arch == builtin.Arch.x86_64) {
            asm volatile (
                \\         push   %%rcx
                \\         cmp    $0x1000,%%rax
                \\         lea    16(%%rsp),%%rcx     // rsp before calling this routine -> rcx
                \\         jb     1f
                \\ 2:
                \\         sub    $0x1000,%%rcx
                \\         test   %%rcx,(%%rcx)
                \\         sub    $0x1000,%%rax
                \\         cmp    $0x1000,%%rax
                \\         ja     2b
                \\ 1:
                \\         sub    %%rax,%%rcx
                \\         test   %%rcx,(%%rcx)
                \\ 
                \\         lea    8(%%rsp),%%rax     // load pointer to the return address into rax
                \\         mov    %%rcx,%%rsp        // install the new top of stack pointer into rsp
                \\         mov    -8(%%rax),%%rcx    // restore rcx
                \\         push   (%%rax)           // push return address onto the stack
                \\         sub    %%rsp,%%rax        // restore the original value in rax
                \\         ret
            );
            unreachable;
        }
    }

    @setGlobalLinkage(__chkstk, builtin.GlobalLinkage.Internal);
}
```

Now it's:

```zig
comptime {
    if (builtin.os == builtin.Os.windows and builtin.arch == builtin.Arch.x86_64) {
        export __chkstk = windows_check_stack;
    }
}

nakedcc fn windows_check_stack() {
    @setDebugSafety(this, false);

    asm volatile (
        \\         push   %%rcx
        \\         cmp    $0x1000,%%rax
        \\         lea    16(%%rsp),%%rcx     // rsp before calling this routine -> rcx
        \\         jb     1f
        \\ 2:
        \\         sub    $0x1000,%%rcx
        \\         test   %%rcx,(%%rcx)
        \\         sub    $0x1000,%%rax
        \\         cmp    $0x1000,%%rax
        \\         ja     2b
        \\ 1:
        \\         sub    %%rax,%%rcx
        \\         test   %%rcx,(%%rcx)
        \\ 
        \\         lea    8(%%rsp),%%rax     // load pointer to the return address into rax
        \\         mov    %%rcx,%%rsp        // install the new top of stack pointer into rsp
        \\         mov    -8(%%rax),%%rcx    // restore rcx
        \\         push   (%%rax)           // push return address onto the stack
        \\         sub    %%rsp,%%rax        // restore the original value in rax
        \\         ret
    );
    unreachable;
}
```
