### ISSUE TITLE
initialization of empty structs

### ISSUE THREAD

**Issue by PavelVozenilek** [zig-lang/zig#554]
Copied on request from https://github.com/zig-lang/zig/issues/548#issuecomment-338086782.

Zig requires initialization, even for empty structs:

```
const foo = struct {};

pub fn main() -> %void {

  var f : foo;
}

```
results in :

```
 
O:\zig0.1.1>zig build-exe b.zig
O:\zig0.1.1\b.zig:11:3: error: variables must be initialized
  var f : foo;
  ^

```

While empty struct does not make much of sense, asking for its initialization is IMO error.

**Comment by andrewrk** [comment]
You have 2 options for initializing a struct, whether it has 0 or more fields:

Option 1, recommended, list all the fields in the initializer. With a struct with no fields, there are 0 fields in the initializer. This option is recommended because if you add a field later, you'll get a compiler error here for not initializing all fields.

```zig
var f = foo {}; 
```

Option 2, leave all fields undefined:

```zig
var f: foo = undefined;
```
