### ISSUE TITLE
Make `zig build` fail on absence of build file

### ISSUE THREAD

**Issue by jfo** [zig-lang/zig#748]
Currently, running `zig build` in a directory with no `build.zig` file gives

```
Wrote build.zig template
```

This behavior can be surprising and result in an unwanted file if you accidentally run it in the wrong directory. I suggest `zig build` fail if there is no existing template file and adjusting the current behavior to use a subcommand or flag.

**Comment by SimonN** [comment]
This issue was prompted from my question in IRC today. I gave gave Zig a try, here's my new-user experience:
* Arch 64-bit, building Zig from the github repository works fine, I stuck precisely to the build instructions in the main readme. Nice!
* I navigate to `example/guess_number` and want to build the example game
* Running `zig` (really `../../build/zig`) without arguments prints only usage
* `zig build` is explained first in the usage, I thought I'd try that first then. It writes the template, but produces no executable.
* `zig build` again fails with compile errors in `main.zig`. Surely the example program cannot have this many errors, thus I
* I examine the `build.zig` and see that it expects the source in `src/main.zig` instead of `main.zig`.
* I create directory `src`, move `main.zig` into `src`, and now `zig build` finally works and produces the executable, which then runs well.
* I ask on IRC whether `zig build` is the correct workflow, and jfo's answer was: Yes, it is, except maybe for small single-file programs that don't come with a project; we would run `zig build-exe` on these.

My main language is D where the most popular builder/packager is dub, and `dub` in a non-project directory fails; to initialize a project, you would run `dub init` explicitly.

**Comment by andrewrk** [comment]
100% agree. Apologies for the poor design decision

**Comment by jfo** [comment]
Alright! I'll take a crack at this.

**Comment by SimonN** [comment]
No apologies needed!

Maybe explain `build-exe` in the error when `zig build` fails, as an alternative to suggesting an initialization? E.g.:
```
No build template `build.zig' found.
Initialize a new project with `zig build --init'
or build an executable directly with `zig build-exe main.zig'.
```
Reason: For a small example, it is a good workflow to build directly. For big projects, they would usually ship with a `build.zig`. In neither case, initialization is wanted.
