### ISSUE TITLE
Recursive functions cannot have inferred error sets

### ISSUE THREAD

**Issue by tiehuis** [zig-lang/zig#763]
```
fn foo(i: usize) !usize {
    if (i == 54) {
        return error.Invalid;
    }

    if (i > 0) {
        return 1 + try foo(i - 1);
    } else {
        return 1;
    }
}

test "example" {
    _ = try foo(5);
}
```

Results in the following error.

```
/tmp/t.zig:7:20: error: cannot resolve inferred error set '@typeOf(foo).ReturnType.ErrorSet': function 'foo' not fully analyzed yet
        return 1 + try foo(i - 1);
```

We can work around this by adding an explicit error type.

```
const FooErrors = error {
    Invalid,
};

fn foo(i: usize) FooErrors!usize {
    if (i == 54) {
        return error.Invalid;
    }

    if (i > 0) {
        return 1 + try foo(i - 1);
    } else {
        return 1;
    }
}

test "example" {
    _ = try foo(5);
}
```

This seems like a possibly common occurrence. Is this expected behavior? Is there an easy way to infer recursive functions or is this an inherent limitation? Not sure on the internals.

**Comment by andrewrk** [comment]
Yeah this is expected and an inherent limitation. 

There's a straightforward way to figure out what values should go in the explicit error set - make it empty and look at the compile errors. 

In general, when in doubt with error sets, don't fidget with fancy features too much, just declare an explicit set.

**Comment by tiehuis** [comment]
Alright sounds good.

Just to check. Would it be possible when inferring error sets type, when checking a function call if we know that this is a recursive definition delaying (or adding no errors) to the error set inferrence and waiting until the function is completely inferred? May be on the completely wrong track.

**Comment by andrewrk** [comment]
It is fundamentally possible, but it's actually prevented from working because the c++ zig compiler uses recursion. If we switched analysis to use an explicit stack it would allow this thing you're saying. The problem is that we need the error set to be resolved at the end of the function call analysis, but we already are in the middle of the same function call analysis upwards in the compiler stack. I don't know if that makes sense, I can try to explain more after I've had some sleep.

**Comment by tiehuis** [comment]
No problem I get the general idea.
