### ISSUE TITLE
v0.2.0 linux download link is broken, says "403 forbidden"

### ISSUE THREAD

**Issue by ccll** [zig-lang/zig#999]
![image](https://user-images.githubusercontent.com/5366582/39797640-ac063924-538f-11e8-8b28-1cf3949933ca.png)

Win64 link works fine.

**Comment by tiehuis** [comment]
Sorry about that. Here is the correct link:
https://ziglang.org/download/0.2.0/zig-linux-x86_64-0.2.0.tar.xz

Will update the site now.

**Comment by tiehuis** [comment]
Site should be updated now.

**Comment by tiehuis** [comment]
Unfortunately the problem here is that the 0.2.0 static image was backported without runtime libc determination. Usually this would be set at compile-time but this build was done in a docker-container and so this doesn't work.

Alternatively, you can try the master build which doesn't have this issue. I can look into updating the 0.2.0 binary at some point with a backported patch but not sure when.
https://ziglang.org/builds/zig-linux-x86_64-master.tar.xz

**Comment by ccll** [comment]
Thanks, I'll try the master build.
